### ISSUE TITLE
Plantage de BkgPi2a sur l'événement ClosedBeyondCallCenterScope

### ISSUE THREAD

**Issue by tjpb92** [tjpb92/Bkgpi2a#31]
Lorsqu'il n'y a pas de commentaire dans l'événement ClosedBeyondCallCenterScope, le programme BkpPi2a se plante : 
```
  Evénement no1 : ClosedBeyondCallCenterScope, processUid:69fe9de0-ef9d-4e6b-89e6-ca97d6cf0a98, aggregateUid:0792c5a1-e5c6-5622-51cf-209445682407
Problème lors de l'instanciation de Bkgpi2a
java.lang.NullPointerException
        at bkgpi2a.Bkgpi2a.processClosedBeyondCallCenterScope(Bkgpi2a.java:524)
        at bkgpi2a.Bkgpi2a.syncEvents(Bkgpi2a.java:315)
        at bkgpi2a.Bkgpi2a.<init>(Bkgpi2a.java:243)
        at bkgpi2a.Bkgpi2a.main(Bkgpi2a.java:1933)
```

**Plusieurs questions** : 
- Pourquoi, l'événement n'est-il pas marqué en erreur ?
- Pourquoi l'erreur n'est-elle pas détectée par le programme de supervision ?

**Prévoir** : Une alerte dans la cas où trop d'événements seraient en attente de traitement.

Les deux événements concernés sont : 
```
> db.events.find({"processUid":"69fe9de0-ef9d-4e6b-89e6-ca97d6cf0a98"}).pretty()
{
        "_id" : ObjectId("5d27506a2bd24b13fd7f8ab2"),
        "processUid" : "69fe9de0-ef9d-4e6b-89e6-ca97d6cf0a98",
        "aggregateUid" : "0792c5a1-e5c6-5622-51cf-209445682407",
        "sentDate" : "2019-07-11T15:06:08.823Z",
        "eventType" : "ClosedBeyondCallCenterScope",
        "status" : -1,
        "nbError" : 1,
        "operator" : {
                "operatorType" : "ReferencedUser",
                "userUid" : "96d8dae2-d4b5-475a-9395-f3af6c11abf6"
        },
        "closingDate" : "2019-07-11T15:06:08.520Z",
        "comment" : " "
}
```
et
```
> db.events.find({"processUid":"f7092a6d-e6f2-4881-9c36-0acea1a574e1"}).pretty()
{
        "_id" : ObjectId("5d27559b2bd24b1bd0b8f2dc"),
        "processUid" : "f7092a6d-e6f2-4881-9c36-0acea1a574e1",
        "aggregateUid" : "07a532b7-d80c-3398-578f-795afb8ff82a",
        "sentDate" : "2019-07-11T15:27:55.867Z",
        "eventType" : "ClosedBeyondCallCenterScope",
        "status" : 1,
        "nbError" : 0,
        "operator" : {
                "operatorType" : "ReferencedUser",
                "userUid" : "96d8dae2-d4b5-475a-9395-f3af6c11abf6"
        },
        "closingDate" : "2019-07-11T15:27:55.363Z",
        "comment" : " "
}
```

**Comment by tjpb92** [comment]
Nouveau cas de figure : 
```
> db.events.find({"processUid":"3ef280f1-1e31-48a7-99b5-74f8f92a5f57"}).pretty()
{
        "_id" : ObjectId("5d2756202bd24b1c9dfdb49e"),
        "processUid" : "3ef280f1-1e31-48a7-99b5-74f8f92a5f57",
        "aggregateUid" : "8952645e-8999-2fdf-bfa2-294081be8da8",
        "sentDate" : "2019-07-11T15:30:38.576Z",
        "eventType" : "ClosedBeyondCallCenterScope",
        "status" : 0,
        "nbError" : 0,
        "operator" : {
                "operatorType" : "ReferencedUser",
                "userUid" : "96d8dae2-d4b5-475a-9395-f3af6c11abf6"
        },
        "closingDate" : "2019-07-11T15:30:38.039Z",
        "comment" : " "
}
```

**Comment by tjpb92** [comment]
Correction du bug en ligne 524 de _Bkgpi2a.java_
Mais les deux questions posées plus haut restent sans réponse pour l'instant
